#!/bin/bash

RUNNER_SUFFIX=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 5 | head -n 1)
RUNNER_NAME=${RUNNER_NAME:-"builder-${RUNNER_SUFFIX}"}
HOME=/home/runner

cd $HOME

_get_reg_token() {
  echo $(curl -Ls \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${GH_TOKEN}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/orgs/${GH_OWNER}/actions/runners/registration-token \
    | jq .token --raw-output)
}


cleanup() {
  echo "Removing runner ${RUNNER_NAME}"
  sudo -u runner -- ./config.sh remove --token $(_get_reg_token)
}

trap "cleanup" SIGKILL SIGTERM SIGHUP SIGINT EXIT

echo "Configuring ${RUNNER_NAME} builder"
sudo -u runner -- ./config.sh --unattended --url https://github.com/${GH_OWNER} --token $(_get_reg_token) --name ${RUNNER_NAME}

echo "Running ${RUNNER_NAME} builder"
sudo -u runner ./run.sh --once &
wait $!

# not a good idea but how else let s6 die?
exit 1
